### List all messages
GET http://localhost:3000/messages

### Create a new message
POST http://localhost:3000/messages
content-type: application/json

{
  "content": "Poop on my moms butt"
}

### Get one message
GET http://localhost:3000/messages/738